"""empty message

Revision ID: 107ae9efb237
Revises: 576cea460126
Create Date: 2022-04-02 13:21:05.416157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107ae9efb237'
down_revision = '576cea460126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
