"""empty message

Revision ID: 576cea460126
Revises: fdaa9f35729b
Create Date: 2022-04-02 13:19:22.500760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576cea460126'
down_revision = 'fdaa9f35729b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
